[package]
name = "aura-io-cpal"
description = "Real-time audio playback for Aura (CPAL)"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
aura-render = { path = "../aura-render" }
aura-sample = { path = "../aura-sample" }
cpal = { workspace = true }
dasp_sample = { workspace = true }

[dev-dependencies]
